import Head from "next/head";
import Image from "next/image";
import Header from "../src/components/Header";
import TitleHeader from "../src/components/TitleHeader";
import styles from "../styles/Home.module.css";

export default function Home() {
   const texts = [
      {
         id: 1,
         title: "Добро пожаловать на наш сайт о  ",
         heading: "Психическом здоровье!",
         text: "Мы понимаем, что забота о своем психическом благополучии так же важна, как и забота о физическом здоровье. Вот почему мы стремимся предоставить вам инструменты и ресурсы, необходимые для улучшения и поддержания вашего психического здоровья.      ",
         src: "/static/mental-health (1).png",
         isRev: false,
      },
      {
         id: 2,
         title: "Ваш интерактивный помошник!",
         heading: "Измеряй, улучшай",
         text: "На нашем сайте вы найдете множество информации по различным темам психического здоровья, включая управление стрессом, тревогой, депрессией и многим другим. Мы также предлагаем различные тесты, курсы и упражнения, которые помогут вам лучше понять свои мысли и эмоции.",
         src: "/static/mental-health (2).png",
         isRev: true,
      },
      //{
      //  id: 3,
      //  title: "Узнавай и становись здоровым!",
      //  heading: "Ты не один",
      //  text: "На нашем сайте представлены личные истории людей, которые успешно справились со своими собственными проблемами психического здоровья.",
      //  src: "https://assets.website-files.com/5ef0b47911602b652f6a26d7/62fd160352960ef699fd9790_Group%201798-p-800.jpg",
      //  isRev: false,
      //},
      {
         id: 3,
         title: "Если вы находитесь в кризисной ситуации",
         heading: "знайте, что вы не одиноки.",
         text: "Если вы нуждаетесь в немедленной помощи - помощь доступна. Мы составили список экстренных горячих линий и ресурсов, которые доступны круглосуточно и без выходных.",
         src: "/static/mental-health (3).png",
         isRev: false,
      },
   ];

   return (
      <div className={styles.container}>
         <Head>
            <title>Quicsence | We care about your mental health </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <div>
            <section class="py-20 bg-white">
               <div class="flex flex-col px-8 mx-auto space-y-12 max-w-7xl xl:px-12">
                  <TitleHeader
                     title="Ментальное здоровье"
                     text=" Этот сайт предлагает вам инструменты для отслеживания вашего психологического состояния и понимания его влияния на вашу жизнь."
                  />
               </div>

               {texts.map((el) => {
                  return (
                     <Header
                        key={el.id}
                        isRev={el.isRev}
                        title={el.title}
                        src={el.src}
                        text={el.text}
                        heading={el.heading}
                        id={el.id}
                     />
                  );
               })}
            </section>
         </div>
      </div>
   );
}
