import Head from "next/head";
import Image from "next/image";
import Header from "../src/components/Header";
import TitleHeader from "../src/components/TitleHeader";
import styles from "../styles/Home.module.css";

export default function Home() {
  const texts = [
    {
      id: 1,
      title: "Digital therapy",
      heading: "Some Catchy Phrase",
      text: "Crafting your user experience has never been easier, with ourintuitive dragn drop interface you will be creating beatifuldesigns in no time.",
      src: "https://assets.website-files.com/5ef0b47911602b652f6a26d7/6273fb9da1844358fba00efe_Group%201486%20(1).png",
      isRev: false,
    },
    {
      id: 2,
      title: "Manage and measure it",
      heading: "Some Catchy Phrase",
      text: "Crafting your user experience has never been easier, with ourintuitive dragn drop interface you will be creating beatifuldesigns in no time.",
      src: "https://assets.website-files.com/5ef0b47911602b652f6a26d7/62fd160455e2617918c46991_Wellbeing-p-800.jpg",
      isRev: true,
    },
    {
      id: 3,
      title: "Learn and become healthy",
      heading: "Some Catchy Phrase",
      text: "Crafting your user experience has never been easier, with ourintuitive dragn drop interface you will be creating beatifuldesigns in no time.",
      src: "https://assets.website-files.com/5ef0b47911602b652f6a26d7/62fd160352960ef699fd9790_Group%201798-p-800.jpg",
      isRev: false,
    },
    {
      id: 4,
      title: "Take care",
      heading: "Some Catchy Phrase",
      text: "Crafting your user experience has never been easier, with ourintuitive dragn drop interface you will be creating beatifuldesigns in no time.",
      src: "https://assets.website-files.com/5ef0b47911602b652f6a26d7/62fd160455e2617918c46991_Wellbeing-p-800.jpg",
      isRev: true,
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Quicsence | We care about your mental health </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <section class="py-20 bg-white">
          <div class="flex flex-col px-8 mx-auto space-y-12 max-w-7xl xl:px-12">
            <TitleHeader
              title="Mental wellbeing"
              text="Add some nice touches to your interface with our latest designs, components, and templates. We've crafted a beautiful user experience that your visitors will love"
            />
          </div>

          {texts.map((el) => {
            return (
              <Header
                key={el.id}
                isRev={el.isRev}
                title={el.title}
                src={el.src}
                text={el.text}
                heading={el.heading}
                id={el.id}
              />
            );
          })}
        </section>
      </div>
    </div>
  );
}
